---
title: "Class-06-09-2021"
author: "Eesha Singh"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```



```{r get-data, include=FALSE}

data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv")%>%
  select(officer_id, po_race, po_sex)

```

```{r, include=FALSE}
plot_data <- data%>%
  group_by(officer_id)%>%
  summarise(total=n())%>%
  arrange(desc(total))%>%
  mutate(officer_id = as.character(officer_id))%>%
  slice(1:10)
```

```{r}
plot_data%>%
  ggplot(aes(x = officer_id, y = total))+
  geom_col()+
  labs(title = "Complaints about Police Officers in Philidelphia",
       subtitle = "Most complained about Police Officers have more complaints than the average officer",
       x = "Officer",
       y = "Complaints",
       caption = "Data from Financial Times")
```

```{r}
data %>% 
  group_by(officer_id) %>% 
  summarize(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_percentage = compl_total/sum(compl_total)) %>% 
  ggplot(mapping = aes(x = compl_dec, y = compl_percentage))+
  geom_col()+
  labs( title = "In Philadelphia, a Small Group of Officers Generate a Disproportionate Share of\nMisconduct Complaints",
    subtitle = "Distribution of civilian misconduct complaints, by decile",
       x = "Decile",
       y = "Percentage of Complaints",
       caption = " Data from Financial Times")+
  scale_x_continuous(breaks = 1:10)+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))
```

